name: Deploy GitHub Pages

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]  # Cambia "main" por "master" si es tu rama principal
  pull_request:
    branches: [ "master" ]  # Cambia "main" por "master" si es tu rama principal

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instala las dependencias (ajusta este paso según las dependencias de tu proyecto)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Cambia esto según el gestor de paquetes y dependencias de tu proyecto

      # Construye el proyecto (ajusta este paso según tu comando de build)
      - name: Build the project
        run: npm run build  # Cambia esto según el comando de build de tu proyecto

      # Despliega el proyecto en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Cambia esto según el directorio de salida de tu build
